language: node_js
node_js:
- '4.0'
- '9.0'
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: RonVf5rYuCI0Y/hirRDqCANIHwFrt4PSpwIOh+jWGrj4Mq4iRV25WrbgVZ7mU+r4nm2qMHpeMmfxdpj5SBawdXlkLGd64S9F9m5I5I9XNgzFrz0NzvkoJ6b3Y+/yVBQ29j+YswJzLTIhdh0ZFL1B/MoSeyLjHyuICO6oADfwpLMjMb9oh37VeQeEI6RlLytLO7zV4872fp9jAXTOLX+YrWOffi1YuOtdgddmEaz+OlMB3wFGu8aDkr9xnt30X/lKwD/gkDMO4CnB8joruJWhXmf3HmrFCSWc0ZdTAN7uWIYze7mNppfc/X5WNQp04QmJYfMT3MBAOSVDIt/b7AuxTDZsP2bY3dhEQvcX0nF20T8leYZrN9wCISqwanfm2OMJ9WNDCc6/OxPVd8TsztRBpSp1V/cIclqaLF7NqTOrIMGMUiSDapxt+loIE+L4E2djQiS5NaienIcM+Q9CWAXCa/et6BktEVR2RXcHfYmo/5Dkhph3RDoBKpLRgd1g0Ylbx70xu2ddae942s4Xfi6BX6jbgMrUwThYXC2l2ZosZQeRNhXF+l/v3YHJDn2cKuXA3u0B2L+VRs1jVum/KLOssbYw/mkOQ2D9x6S29K5qc7lKkc1+ceSuRTF0ONl6Fwc6zRrK05eal9x/Zo4KRuXgKt6uKA+bhR+DVeMlRKYvwC0=
  file:
    - "hast-util-parse-selector.js"
    - "hast-util-parse-selector.min.js"
  on:
    tags: true
    node: '9.0'
